# NumPy library


## What is NumPy ? 
 NumPy is a Python library used for working with arrays.
 
 It also has functions for working in domain of linear algebra, fourier transform, and matrices.
 
 NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.
 
 NumPy stands for Numerical Python.

## Why NumPy needed ?
 In Python we have lists that serve the purpose of arrays, but they are slow to process.
 
 NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
 
 The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
 
 Arrays are very frequently used in data science, where speed and resources are very important

## Why is NumPy Faster Than Lists?
NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

## Which Language is NumPy written in?
NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.

###  Create a NumPy ndarray Object
NumPy is used to work with arrays. The array object in NumPy is called ndarray.

We can create a NumPy ndarray object by using the array() function.

In [102]:
import numpy as np

x=np.array([1,2,3,4]);
print(x)

[1 2 3 4]


####  0-D Arrays
0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [103]:
y= np.array(1);
print(y);
print(y.ndim)

1
0


####  1-D Arrays

1D arrays,it stores the elements in linear and in a sequence. their is single dimension of all the arrays. 

In [104]:
y=np.array([1,2,3,4])
print(y);
print(y.ndim);

[1 2 3 4]
1


#### 2-D Arrays 

2D arrays are store the elements in linear and grid ways. there are two dimensions of each arrays. these arrays looks like matrices.

for example: 

1 2 3 4 5 

2 4 5 6 7 

2 4 5 7 8 

In [105]:
z= np.array(([2,3,4,5],[25,7,8,6],[5, 7,8,9],[3,6,8,0]));
print(z);
print(z.ndim);

[[ 2  3  4  5]
 [25  7  8  6]
 [ 5  7  8  9]
 [ 3  6  8  0]]
2


####  3-D arrays
An array that has 2-D arrays (matrices) as its elements is called 3-D array.

These are often used to represent a 3rd order tensor.

In [106]:
x=np.array([[[1,3,4,5],[2,5,6,7]],[[1,3,4,5],[2,5,6,7]]]);
print(x);
print("dimension of x is ",x.ndim);

[[[1 3 4 5]
  [2 5 6 7]]

 [[1 3 4 5]
  [2 5 6 7]]]
dimension of x is  3


###  Check Number of Dimensions?
NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.



In [107]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


###  Higher Dimensional Arrays
An array can have any number of dimensions.

When the array is created, you can define the number of dimensions by using the ndmin argument.

In [108]:
x=np.array([2,4,5,6], ndmin=5);
print(x)
print(x.ndim)

[[[[[2 4 5 6]]]]]
5


## NumPy Array Indexing

### Access Array Elements
Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [109]:
arr = np.array([4, 7, 8, 49,9,5,4,7,8,46,75,5,7,6,6,4,563,64,563,76,46,45,7,47,56,5])

print(arr[0]);
print(arr[3]);

print(arr[3]+arr[4]);

4
49
58


### Access 2-D Arrays
To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

In [110]:
arr1= np.array([[2,3,4,5],[23,5,7,8],[2,4,6,7]])

print(arr1)
print(arr1[2,2])

[[ 2  3  4  5]
 [23  5  7  8]
 [ 2  4  6  7]]
6


## Access 3-D Arrays
To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [111]:
x= np.array([[[1,3,4,6,],[1,4,6,7]],[[3,6,8,9],[3,6,7,9]]]);
print(x)

print(x[0,1,1]);

[[[1 3 4 6]
  [1 4 6 7]]

 [[3 6 8 9]
  [3 6 7 9]]]
4


#### Explanation
x[0, 1, 1] prints the value 4.

And this is why:

The first number represents the first dimension, which contains two arrays:
[[1 3 4 6]
  [1 4 6 7]]
and:
 [[3 6 8 9]
  [3 6 7 9]]

Since we selected 0, we are left with the first array:
[[1 3 4 6]
  [1 4 6 7]]

The second number represents the second dimension, which also contains two arrays:
[1 3 4 6]
and:
[1 4 6 7]
Since we selected 1, we are left with the second array:
[1 4 6 7]

The third number represents the third dimension, which contains four values:
1 4 6 7

Since we selected 1, we end up with the 2nd value:
4

### Negative Indexing
Use negative indexing to access an array from the end.

In [112]:

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[-1, -2])

Last element from 2nd dim:  9


### Explanation 

here arr[-1,-2];

there are two array 

1: [1,2,3,4,5] 

and 

2: [6,7,8,9,10]

-1 select the array from end of the arr.

means [6,7,8,9,10]

-2 select the 2nd last element from the array [6,7,8,9,10]

means answer is 9 

## NumPy Array Slicing

### Slicing arrays
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [113]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:4])

# Slice elements from index 4 to the end of the array:

print(arr[4:])

#Slice elements from index 4 to the first of the array and index 4 (not included):

print(arr[:4]);

#Negative Slicing
#Use the minus operator to refer to an index from the end:

print(arr[-3:-1]);

#STEP
#Use the step value to determine the step of the slicing:
print(arr[2:7:2]);

#Return every other element from the entire array:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])
print(arr[::3]);

[2 3 4]
[5 6 7]
[1 2 3 4]
[5 6]
[3 5 7]
[1 3 5 7]
[1 4 7]


#### Slicing 2-D Arrays


In [114]:
a= np.array([[1,2,3,5],[4,6,9,0]]);

print(a[1,1:3]); # not included 3
print(a[0:2,2]); # here show 2nd index value of both the array
print(a[1:2,2]); # here show 2nd  index value of 2nd array 

#From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:

print(a[0:2, 1:2]) #2nd indexed value not included


[6 9]
[3 9]
[9]
[[2]
 [6]]


## NumPy Data Types

### Data Types in Python
By default Python have these data types:

strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"

integer - used to represent integer numbers. e.g. -1, -2, -3

float - used to represent real numbers. e.g. 1.2, 42.42

boolean - used to represent True or False.

complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.

### Data Types in NumPy
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer

b - boolean

u - unsigned integer

f - float

c - complex float

m - timedelta

M - datetime

O - object

S - string

U - unicode string

V - fixed chunk of memory for other type ( void )

### Checking the Data Type of an Array
The NumPy array object has a property called dtype that returns the data type of the array:

In [115]:
a= np.array(["Apple","bannana"]);
b= np.array([1,2,4,5,]);
c=np.array(['a','b','c']);

print(a.dtype);
print(b.dtype);
print(c.dtype);


<U7
int32
<U1


### Creating Arrays With a Defined Data Type
We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements:

In [116]:
x= np.array([1,2,34,5], dtype='S'); # create array of string type
print(x)
print(x.dtype);

y=np.array([1,2,34,5], dtype='i4'); # create array of intiger 4-bytes 
print(y)
print(y.dtype);

# y1= np.array(['a','b','5','3'],dtype='i4');
# print(y1)
# print(y1.dtype);

#  Cell In[249], line 9
#       6 print(y)
#       7 print(y.dtype);
# ----> 9 y1= np.array(['a','b','5','3'],dtype='i4');
#      10 print(y1)
#      11 print(y1.dtype);

# ValueError: invalid literal for int() with base 10: 'a'

z=np.array([1,2,34,5],dtype='f');
print(z)
print(z.dtype);

[b'1' b'2' b'34' b'5']
|S2
[ 1  2 34  5]
int32
[ 1.  2. 34.  5.]
float32


## Converting Data Type on Existing Arrays
The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

In [117]:
x= np.array([1,3,5,6,7]);

newX= x.astype(float);

print(x,newX)

print(x.dtype,newX.dtype);

y=x.astype('S')
print(y,y.dtype);

[1 3 5 6 7] [1. 3. 5. 6. 7.]
int32 float64
[b'1' b'3' b'5' b'6' b'7'] |S11


## NumPy Array Copy vs View

### The Difference Between Copy and View
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

#### Copy:

In [118]:
x=np.array([2,4,56,8]);
y=x.copy(); # it will create new array as copy of x
x[0]=78;

print(x,'\n',y);

[78  4 56  8] 
 [ 2  4 56  8]


#### View:

In [119]:
x=np.array([2,4,56,8]);
y=x.view(); # it will take a referance of x
x[0]=78;
print(x,'\n',y);

y[2]=79;
print(x,'\n',y);

[78  4 56  8] 
 [78  4 56  8]
[78  4 79  8] 
 [78  4 79  8]


### Check if Array Owns its Data
As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

Every NumPy array has the attribute base that returns None if the array owns the data.

Otherwise, the base  attribute refers to the original object.

In [120]:
x=np.array([2,4,56,8]);
y=x.view();
z=x.copy();

print(x,'\n',y,'\n',z);
print(x.base) #it will show none because x has thier own data
print(y.base) # it will show the object [2,4,56,8] because y has not thier own data 
print(z.base) #it will show none because z has thier own data which copied from x


[ 2  4 56  8] 
 [ 2  4 56  8] 
 [ 2  4 56  8]
None
[ 2  4 56  8]
None


## NumPy Array Shape

### Shape of an Array
The shape of an array is the number of elements in each dimension.

NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

In [121]:
import numpy as np;
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

arr=np.array([1,23,4,5,6], ndmin=5)

print(arr.shape)



(2, 4)
(1, 1, 1, 1, 5)


Integers at every index tells about the number of elements the corresponding dimension has.

In the example above at index-4 we have value 5, so we can say that 5th ( 4 + 1 th) dimension has 5 elements.

## NumPy Array Reshaping

### Reshaping arrays

Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [122]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

newarr= arr.reshape(2,3,2)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


### Can We Reshape Into any Shape?
Yes, as long as the elements required for reshaping are equal in both shapes.

We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.

In [123]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2,4 )

print(newarr)

newarr= arr.reshape(3,3)

print(newarr)

[[1 2 3 4]
 [5 6 7 8]]


ValueError: cannot reshape array of size 8 into shape (3,3)

### Returns Copy or View?

In [ ]:
print(newarr.base);


This means it ia a view 

### Unknown Dimension
You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.

In [134]:
arr= np.array([1,23,4,5,6,7,8,5,5,7]);

newarr=arr.reshape(2,5);

print(newarr);

newarr= arr.reshape(-1,2,1)
print(newarr);

[[ 1 23  4  5  6]
 [ 7  8  5  5  7]]
[[[ 1]
  [23]]

 [[ 4]
  [ 5]]

 [[ 6]
  [ 7]]

 [[ 8]
  [ 5]]

 [[ 5]
  [ 7]]]


## NumPy Array Iterating

### Iterating Arrays
Iterating means going through elements one by one.

As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

If we iterate on a 1-D array it will go through each element one by one.

In [133]:
x= np.array([1,2,43,5,6,7]);

for a in x :
    print(a)

1
2
43
5
6
7


For 2-D :

In [132]:
y= np.array([[2,3,45],[2,4,56]]);

for a in y :
  print(a)

for a in y :
  for b in a:
   print(b)

[ 2  3 45]
[ 2  4 56]
2
3
45
2
4
56


For 3-D array:

In [131]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

for x in arr:
  for y in x:
     for z in y:
       print(z)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
1
2
3
4
5
6
7
8
9
10
11
12


### Iterating Arrays Using nditer()
The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples.

In [130]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])


for x in arr:
  print(x) 
   
for a in np.nditer(arr):
    print(a);

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
1
2
3
4
5
6
7
8
9
10
11
12


### Iterating Array With Different Data Types
We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.

NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].

In [129]:
arr= np.array([[1,23,4,5],[5,6,7,9]]);

for x in np.nditer(arr,flags=['buffered'],op_dtypes='S'):

    print(x)

print(arr)

b'1'
b'23'
b'4'
b'5'
b'5'
b'6'
b'7'
b'9'
[[ 1 23  4  5]
 [ 5  6  7  9]]


### Iterating With Different Step Size
We can use filtering and followed by iteration.

2-D Array:

In [128]:
arr= np.array([[2,3,4],[4,5,76],[1,2,3],[3,4,5]]);

for a in np.nditer(arr[:,::2]):
    print(a);

2
4
4
76
1
3
3
5


3-D Array:

In [127]:
arr= np.array([[[2,3,4],[4,5,76]],[[1,2,3],[3,4,5]]]);

for a in np.nditer(arr[:,:,::2]):
    print(a);
    

2
4
4
76
1
3
3
5


#### Explanation
###### arr= np.array([[[2,3,4],[4,5,76]],[[1,2,3],[3,4,5]]])

This line creates a 3-dimensional NumPy array. The outermost list contains two lists, each of which contains two more lists of three elements.

###### for a in np.nditer(arr[:,:,::2]): 

This line iterates over the array using np.nditer, which is a function that allows efficient multi-dimensional iteration over arrays. The arr[:,:,::2] part is slicing the array. The : means take everything along this dimension. The ::2 means take every other element along the last dimension.

###### print(a)

This line prints each element that the iterator goes over

### Enumerated Iteration Using ndenumerate()
Enumeration means mentioning sequence number of somethings one by one.

Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.

for 1-D array:

In [126]:
arr= np.array([1,2,3,4,5,6,76,8,9]);

for idx,a in np.ndenumerate(arr):
    print(idx,a)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(5,) 6
(6,) 76
(7,) 8
(8,) 9


For 2-D array:

In [125]:
arr= np.array([[1,3,4,5],[5,6,8,0]]);

for idx,a in np.ndenumerate(arr):
    print(idx,a)

(0, 0) 1
(0, 1) 3
(0, 2) 4
(0, 3) 5
(1, 0) 5
(1, 1) 6
(1, 2) 8
(1, 3) 0


for 3-D array:

In [124]:
arr=np.array([[[1,2,3,4,5],[2,4,5,6,7]],[[9,4,5,7,3],[27,39,92,90,2]]]);

for i,a in np.ndenumerate(arr):
    print(i,a)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 0, 4) 5
(0, 1, 0) 2
(0, 1, 1) 4
(0, 1, 2) 5
(0, 1, 3) 6
(0, 1, 4) 7
(1, 0, 0) 9
(1, 0, 1) 4
(1, 0, 2) 5
(1, 0, 3) 7
(1, 0, 4) 3
(1, 1, 0) 27
(1, 1, 1) 39
(1, 1, 2) 92
(1, 1, 3) 90
(1, 1, 4) 2
