# NumPy library


## What is NumPy ? 
 NumPy is a Python library used for working with arrays.
 
 It also has functions for working in domain of linear algebra, fourier transform, and matrices.
 
 NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.
 
 NumPy stands for Numerical Python.

## Why NumPy needed ?
 In Python we have lists that serve the purpose of arrays, but they are slow to process.
 
 NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
 
 The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
 
 Arrays are very frequently used in data science, where speed and resources are very important

## Why is NumPy Faster Than Lists?
NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

## Which Language is NumPy written in?
NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.

###  Create a NumPy ndarray Object
NumPy is used to work with arrays. The array object in NumPy is called ndarray.

We can create a NumPy ndarray object by using the array() function.

In [53]:
import numpy as np

x=np.array([1,2,3,4]);
print(x)

[1 2 3 4]


####  0-D Arrays
0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [54]:
y= np.array(1);
print(y);
print(y.ndim)

1
0


####  1-D Arrays

1D arrays,it stores the elements in linear and in a sequence. their is single dimension of all the arrays. 

In [55]:
y=np.array([1,2,3,4])
print(y);
print(y.ndim);

[1 2 3 4]
1


#### 2-D Arrays 

2D arrays are store the elements in linear and grid ways. there are two dimensions of each arrays. these arrays looks like matrices.

for example: 

1 2 3 4 5 

2 4 5 6 7 

2 4 5 7 8 

In [56]:
z= np.array(([2,3,4,5],[25,7,8,6],[5, 7,8,9],[3,6,8,0]));
print(z);
print(z.ndim);

[[ 2  3  4  5]
 [25  7  8  6]
 [ 5  7  8  9]
 [ 3  6  8  0]]
2


####  3-D arrays
An array that has 2-D arrays (matrices) as its elements is called 3-D array.

These are often used to represent a 3rd order tensor.

In [57]:
x=np.array([[[1,3,4,5],[2,5,6,7]],[[1,3,4,5],[2,5,6,7]]]);
print(x);
print("dimension of x is ",x.ndim);

[[[1 3 4 5]
  [2 5 6 7]]

 [[1 3 4 5]
  [2 5 6 7]]]
dimension of x is  3


###  Check Number of Dimensions?
NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.



In [58]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


###  Higher Dimensional Arrays
An array can have any number of dimensions.

When the array is created, you can define the number of dimensions by using the ndmin argument.

In [59]:
x=np.array([2,4,5,6], ndmin=5);
print(x)
print(x.ndim)

[[[[[2 4 5 6]]]]]
5


## NumPy Array Indexing

### Access Array Elements
Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [60]:
arr = np.array([4, 7, 8, 49,9,5,4,7,8,46,75,5,7,6,6,4,563,64,563,76,46,45,7,47,56,5])

print(arr[0]);
print(arr[3]);

print(arr[3]+arr[4]);

4
49
58


### Access 2-D Arrays
To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

In [61]:
arr1= np.array([[2,3,4,5],[23,5,7,8],[2,4,6,7]])

print(arr1)
print(arr1[2,2])

[[ 2  3  4  5]
 [23  5  7  8]
 [ 2  4  6  7]]
6


## Access 3-D Arrays
To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [62]:
x= np.array([[[1,3,4,6,],[1,4,6,7]],[[3,6,8,9],[3,6,7,9]]]);
print(x)

print(x[0,1,1]);

[[[1 3 4 6]
  [1 4 6 7]]

 [[3 6 8 9]
  [3 6 7 9]]]
4


#### Explanation
x[0, 1, 1] prints the value 4.

And this is why:

The first number represents the first dimension, which contains two arrays:
[[1 3 4 6]
  [1 4 6 7]]
and:
 [[3 6 8 9]
  [3 6 7 9]]

Since we selected 0, we are left with the first array:
[[1 3 4 6]
  [1 4 6 7]]

The second number represents the second dimension, which also contains two arrays:
[1 3 4 6]
and:
[1 4 6 7]
Since we selected 1, we are left with the second array:
[1 4 6 7]

The third number represents the third dimension, which contains four values:
1 4 6 7

Since we selected 1, we end up with the 2nd value:
4

### Negative Indexing
Use negative indexing to access an array from the end.

In [63]:

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[-1, -2])

Last element from 2nd dim:  9


### Explanation 

here arr[-1,-2];

there are two array 

1: [1,2,3,4,5] 

and 

2: [6,7,8,9,10]

-1 select the array from end of the arr.

means [6,7,8,9,10]

-2 select the 2nd last element from the array [6,7,8,9,10]

means answer is 9 

## NumPy Array Slicing

### Slicing arrays
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [64]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:4])

# Slice elements from index 4 to the end of the array:

print(arr[4:])

#Slice elements from index 4 to the first of the array and index 4 (not included):

print(arr[:4]);

#Negative Slicing
#Use the minus operator to refer to an index from the end:

print(arr[-3:-1]);

#STEP
#Use the step value to determine the step of the slicing:
print(arr[2:7:2]);

#Return every other element from the entire array:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])
print(arr[::3]);

[2 3 4]
[5 6 7]
[1 2 3 4]
[5 6]
[3 5 7]
[1 3 5 7]
[1 4 7]


#### Slicing 2-D Arrays


In [65]:
a= np.array([[1,2,3,5],[4,6,9,0]]);

print(a[1,1:3]); # not included 3
print(a[0:2,2]); # here show 2nd index value of both the array
print(a[1:2,2]); # here show 2nd  index value of 2nd array 

#From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:

print(a[0:2, 1:2]) #2nd indexed value not included


[6 9]
[3 9]
[9]
[[2]
 [6]]


## NumPy Data Types

### Data Types in Python
By default Python have these data types:

strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"

integer - used to represent integer numbers. e.g. -1, -2, -3

float - used to represent real numbers. e.g. 1.2, 42.42

boolean - used to represent True or False.

complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.

### Data Types in NumPy
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer

b - boolean

u - unsigned integer

f - float

c - complex float

m - timedelta

M - datetime

O - object

S - string

U - unicode string

V - fixed chunk of memory for other type ( void )

### Checking the Data Type of an Array
The NumPy array object has a property called dtype that returns the data type of the array:

In [66]:
a= np.array(["Apple","bannana"]);
b= np.array([1,2,4,5,]);
c=np.array(['a','b','c']);

print(a.dtype);
print(b.dtype);
print(c.dtype);


<U7
int32
<U1


### Creating Arrays With a Defined Data Type
We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements:

In [67]:
x= np.array([1,2,34,5], dtype='S'); # create array of string type
print(x)
print(x.dtype);

y=np.array([1,2,34,5], dtype='i4'); # create array of intiger 4-bytes 
print(y)
print(y.dtype);

# y1= np.array(['a','b','5','3'],dtype='i4');
# print(y1)
# print(y1.dtype);

#  Cell In[249], line 9
#       6 print(y)
#       7 print(y.dtype);
# ----> 9 y1= np.array(['a','b','5','3'],dtype='i4');
#      10 print(y1)
#      11 print(y1.dtype);

# ValueError: invalid literal for int() with base 10: 'a'

z=np.array([1,2,34,5],dtype='f');
print(z)
print(z.dtype);

[b'1' b'2' b'34' b'5']
|S2
[ 1  2 34  5]
int32
[ 1.  2. 34.  5.]
float32


## Converting Data Type on Existing Arrays
The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

In [68]:
x= np.array([1,3,5,6,7]);

newX= x.astype(float);

print(x,newX)

print(x.dtype,newX.dtype);

y=x.astype('S')
print(y,y.dtype);

[1 3 5 6 7] [1. 3. 5. 6. 7.]
int32 float64
[b'1' b'3' b'5' b'6' b'7'] |S11


## NumPy Array Copy vs View

### The Difference Between Copy and View
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

#### Copy:

In [69]:
x=np.array([2,4,56,8]);
y=x.copy(); # it will create new array as copy of x
x[0]=78;

print(x,'\n',y);

[78  4 56  8] 
 [ 2  4 56  8]


#### View:

In [70]:
x=np.array([2,4,56,8]);
y=x.view(); # it will take a referance of x
x[0]=78;
print(x,'\n',y);

y[2]=79;
print(x,'\n',y);

[78  4 56  8] 
 [78  4 56  8]
[78  4 79  8] 
 [78  4 79  8]


### Check if Array Owns its Data
As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

Every NumPy array has the attribute base that returns None if the array owns the data.

Otherwise, the base  attribute refers to the original object.

In [71]:
x=np.array([2,4,56,8]);
y=x.view();
z=x.copy();

print(x,'\n',y,'\n',z);
print(x.base) #it will show none because x has thier own data
print(y.base) # it will show the object [2,4,56,8] because y has not thier own data 
print(z.base) #it will show none because z has thier own data which copied from x


[ 2  4 56  8] 
 [ 2  4 56  8] 
 [ 2  4 56  8]
None
[ 2  4 56  8]
None


## NumPy Array Shape

### Shape of an Array
The shape of an array is the number of elements in each dimension.

NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

In [72]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)
